spring.application.name=practica2

# ===== POSTGRESQL (Docker en localhost:5432) =====
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sisdis_db
spring.datasource.username=sisdis
spring.datasource.password=sisdis123

# ===== JPA / HIBERNATE =====
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== SERVIDOR =====
server.port=8080

# ===== URL DE LA API PYTHON FLASK =====
python.api.base-url=http://localhost:5000

# ===== THYMELEAF =====
spring.thymeleaf.cache=false
